export const ALGORITHMS = [
  {
    id: "bubble",
    name: "Bubble Sort",
    func: "runBubbleSort",
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    applications: "Used in teaching and basic visualization of sorting steps.",
  },
  {
    id: "insertion",
    name: "Insertion Sort",
    func: "runInsertionSort",
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    applications: "Good for small datasets or nearly sorted arrays.",
  },
  {
    id: "selection",
    name: "Selection Sort",
    func: "runSelectionSort",
    best: "O(n²)",
    average: "O(n²)",
    worst: "O(n²)",
    applications: "Useful when memory writes are costly.",
  },
  {
    id: "merge",
    name: "Merge Sort",
    func: "runMergeSort",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    applications: "Efficient for large datasets and linked lists.",
  },
  {
    id: "quick",
    name: "Quick Sort",
    func: "runQuickSort",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n²)",
    applications: "Widely used in system-level sorting (like C’s qsort).",
  },
  {
    id: "heap",
    name: "Heap Sort",
    func: "runHeapSort",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    applications: "Used in priority queues and heap-based structures.",
  },
  {
    id: "shell",
    name: "Shell Sort",
    func: "runShellSort",
    best: "O(n log n)",
    average: "O(n^(3/2))",
    worst: "O(n²)",
    applications: "Improves insertion sort for larger arrays.",
  },
];
